# Generated by Django 2.1.4 on 2018-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20181226_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='form_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6),
        ),
        migrations.AddField(
            model_name='placement',
            name='form_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6),
        ),
    ]
