# Generated by Django 2.1.4 on 2018-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[(1, 'Computer Science and Engineering'), (2, 'Electronics and Communication Engineering'), (3, 'Electrical Engineering'), (4, 'Metallurgical and Materials Engineering'), (5, 'Biotechnology'), (6, 'Information Technology'), (7, 'Civil Engineering'), (8, 'Chemical Engineering')], default='None', max_length=25),
        ),
    ]
