# Generated by Django 2.1.4 on 2018-12-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('cs', 'Computer Science and Engineering'), ('ec', 'Electronics and Communication Engineering'), ('ee', 'Electrical Engineering'), ('mm', 'Metallurgical and Materials Engineering'), ('bt', 'Biotechnology'), ('it', 'Information Technology'), ('cv', 'Civil Engineering'), ('cm', 'Chemical Engineering')], default='None', max_length=25),
        ),
    ]
